parameters:

services:
    _defaults:
        autowire: false
        autoconfigure: false

    client.http.steam:
        class: DemigrantSoft\Infrastructure\Steam\SteamClient
        arguments:
            - "%env(STEAM_API_KEY)%"

    client.communication.telegram:
        class: DemigrantSoft\Infrastructure\Communication\TelegramClient
        arguments:
            - '%env(TELEGRAM_TOKEN)%'
            - '%env(TELEGRAM_GROUP_CHAT_ID)%'
            - '%env(TELEGRAM_ADMIN_CHAT_ID)%'

    command.check:
        class: DemigrantSoft\Entrypoint\Command\CheckNewGamesCommand
        arguments:
            - '@client.http.steam'
            - '@client.communication.telegram'
            - '%env(STEAM_ID_64)%'
        tags:
            - { name: console.command, command: 'game:check' }